import os
from io import BytesIO
import pdfplumber
import asyncio
from playwright.async_api import async_playwright
import tempfile


def extract_pdf_text(pdf_binary: bytes) -> str:
    with pdfplumber.open(BytesIO(pdf_binary)) as pdf:
        text = ""
        for page in pdf.pages:
            text += page.extract_text() or ""
    return text

def purify_llm_generted_html_code(code: str) -> str:
    """
    Purify the code generated by LLM to remove unnecessary parts.
    """
    code = code.strip()
    purified_lines = []
    if code.startswith("```html"):
        code = code[7:].strip()
    if code.endswith("```"):
        code = code[:-3].strip()
    
    return code

async def get_computed_styles(html: str, tag_id: str) -> dict:
    with tempfile.NamedTemporaryFile(delete=False, suffix=".html", mode="w", encoding="utf-8") as f:
        f.write(html)
        temp_html_path = f.name

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.goto("file://" + temp_html_path)

        js_code = f"""
        () => {{
            const elem = document.getElementById("{tag_id}");
            if (!elem) return null;
            const computed = getComputedStyle(elem);
            const result = {{}};
            for (let i = 0; i < computed.length; i++) {{
                const prop = computed[i];
                result[prop] = computed.getPropertyValue(prop);
            }}
            return result;
        }}
        """
        styles = await page.evaluate(js_code)

        await browser.close()
        os.remove(temp_html_path)
        return styles